apiVersion: apps/v1
kind: Deployment
metadata:
  name: avlservice1
spec:
  selector:
    matchLabels:
      app: avlservice1
  replicas: 1
  template:
    metadata:
      labels:
        app: avlservice1
    spec:
      containers:
      - name: avlservice1
        image: zvavltest/avlservice-repo:avlserviceimage1v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
