apiVersion: v1
kind: Service
metadata:
  name: avlservice1
  labels:
    app: avlservice1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "service1chart.selectorLabels" . | nindent 4 }}
