name: CI

env:
  IMAGENAME1: ${{ secrets.DOCKERHUB_USERNAME }}/avlservice-repo:avlserviceimage1
  IMAGENAME2: ${{ secrets.DOCKERHUB_USERNAME }}/avlservice-repo:avlserviceimage2

on:
  push:
    tags:
      - v*.*

  workflow_dispatch:

jobs:
  cijob:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        
      - name: Build Docker images
        id: docker_build
        run: |
         docker build -t ${{ env.IMAGENAME1 }}${{ env.VERSION }} ./service1
         docker build -t ${{ env.IMAGENAME2 }}${{ env.VERSION }} ./service2

      - name: 'Unit test'
        run: echo "Unit test passed"

      - name: 'Integration test'
        run: echo "Integration test passed"

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Push to DockerHub'
        run: |
          docker push ${{ env.IMAGENAME1 }}${{ env.VERSION }}
          docker push ${{ env.IMAGENAME2 }}${{ env.VERSION }}
          
          
